- set_fact: redis_max_memory_bytes={{ ansible_memtotal_mb * 0.2 * 1024 * 1024 * 1024 | round | int }}

- file: path=/etc/redis state=directory

- name: update redis config
  template: "src=redis.conf.j2 dest=/etc/redis/redis.conf"
  notify:
    - restart redis server

- name: install redis-server
  apt: 'name=redis-server=3:3.0* state=present'

- name: run redis-server with monit
  template: src=roles/monit/templates/monit/redis-server.conf.j2 dest=/etc/monit/conf.d/redis-server.conf
  notify: reload monit

- name: flush handlers
  meta: flush_handlers
