- name: install certbot dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates
    - apache2
- name: install Python cryptography module
  pip: name=cryptography

- name: download certbot
  become: yes
  become_user: '{{ deploy_user }}'
  get_url: >
    url=https://dl.eff.org/certbot-auto
    dest=/home/{{ deploy_user }}/certbot-auto

- name: generate certs
  become: yes
  # become_user: '{{ deploy_user }}'
  shell: "/home/{{ deploy_user }}/certbot-auto certonly --webroot -w /home/{{ deploy_user }}/www/switchboard.chat/current/public {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"

- name: hup nginx
  service: name=nginx state=reloaded
