sudo: false

language: node_js

node_js:
  - "4.0"
  - "5.0"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

os:
  - linux

script: npm run test

services:
  - redis-server
  - mysql
  - elasticsearch

before_script:
  - mysql -e 'create database IF NOT EXISTS switchboard_test'
