# http://mmonit.com/monit/dist/monit-5.11.tar.gz

- name: get current monit version
  shell: "monit -V | grep version | awk '{print $5}'"
  register: current_monit_version
  ignore_errors: True

- name: download monit
  get_url: >
    url=http://mmonit.com/monit/dist/monit-{{ monit_version }}.tar.gz
    dest=/tmp/monit-{{ monit_version }}.tar.gz
  when: current_monit_version.stdout != monit_version

- file: path=/tmp/monit-{{ monit_version }} state=directory
  when: current_monit_version.stdout != monit_version

- file: path=/var/monit        state=directory
- file: path=/etc/monit/conf.d state=directory

- name: extract monit
  unarchive: >
    copy=no
    src=/tmp/monit-{{ monit_version }}.tar.gz
    dest=/tmp/
  when: current_monit_version.stdout != monit_version

- name: build monit
  shell: >
    chdir=/tmp/monit-{{ monit_version }}
    ./configure
    && make
    && make install
  when: current_monit_version.stdout != monit_version
  notify: restart monit

- name: /etc/init.d/monit
  template: src=monit_init.j2 dest=/etc/init.d/monit mode=0766 owner=root
  notify: restart monit

- name: /etc/monit/monitrc
  template: src=monitrc.j2 dest=/etc/monit/monitrc
  notify: restart monit

- name: link up the monitrc # this is needed so that the monit install can be called by command line (monit status, etc)
  file: src=/etc/monit/monitrc dest=/usr/local/etc/monitrc state=link

- name: set startup levels
  shell: >
    /usr/sbin/update-rc.d monit defaults

- name: flush handlers
  meta: flush_handlers
