# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Build the iOS application'
  private_lane :build do
    # certificates
    increment_build_number(xcodeproj: './ios/Switchboard.xcodeproj')
    gym(
      scheme: 'Switchboard',
      project: './ios/Switchboard.xcodeproj',
      build_path: './tmp/build',
      archive_path: './tmp/archive'
    )
  end

  desc 'Ship to Testflight'
  lane :beta do
    get_certificates
    get_provisioning_profile
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/Switchboard.xcodeproj')
    push_to_git_remote
  end
end
