# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ensure_git_branch
  # ensure_git_status_clean
  # git_pull
end

platform :ios do
  # desc 'Fetch certificates and provisioning profiles'
  # lane :certificates do
  #   match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
  #   match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
  # end

  desc 'Build the iOS application'
  private_lane :build do
    # certificates
    increment_build_number(xcodeproj: './ios/name.xcodeproj')
    gym(scheme: 'name', project: './ios/name.xcodeproj')
  end

  desc 'Ship to Testflight'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/name.xcodeproj')
    push_to_git_remote
  end
end
