---

- name: install base packages
  apt: 'name={{ item }} state=present'
  with_items:
     - build-essential
     - htop
     - unzip
     - bc
     - screen
     - landscape-common
     - sysstat
     - git-core
     - iftop
     - iptables
     - ntp
     - python-pip
     - python-dev
     - logrotate
     - libpam0g
     - libpam0g-dev
     - libmysqlclient-dev

- apt: name=apparmor state=absent
