- name: Autoaccept license for Java
  debconf: name="oracle-java8-installer" setting="shared/accepted-oracle-license-v1-1" vtype="select" value="true"

- name: Install Java 8
  apt: pkg=oracle-java8-installer state=latest install_recommends=yes

- name: Set Java 8 Env
  apt: pkg=oracle-java8-set-default state=latest install_recommends=yes