- name: install ruby deps
  apt: 'name={{ item }} state=present'
  with_items:
    - zlib1g
    - zlib1g-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libncurses5-dev
    - libreadline-dev
    - libyaml-dev
    - libc6-dev
    - libc6

- name: install ruby packages
  apt: 'name={{ item }} state=present'
  with_items:
     - "ruby2.1"
     - "ruby2.1-dev"

- name: install bundler
  command: 'gem install bundler'
  args:
    creates: '/usr/local/bin/bundler'