- name: ensure the nginx dir
  file: path=/etc/nginx state=directory owner=root

- name: ensure the nginx log dir
  file: path=/var/log/nginx state=directory owner=nobody group=nogroup

- name: ensure the default site is removed
  file: path=/etc/nginx/sites-{{ item }}/default state=absent
  with_items:
    - enabled
    - available
  notify:
    - restart nginx

- name: nginx.conf
  template: src=production.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: SSL KEYs
  template: src=certs/chained.pem dest=/etc/nginx/chained.pem
  notify:
    - reload nginx

- name: SSL PEMs
  template: src=certs/domain.key dest=/etc/nginx/domain.key
  notify:
    - reload nginx

- name: DHE Keys
  template: src=certs/dhparam.pem dest=/etc/nginx/dhparam.pem
  notify:
    - reload nginx

- name: install nginx
  # apt: pkg=nginx=1.8.0-1+trusty1 state=present
  apt: pkg=nginx state=present
  notify:
    - restart nginx

- name: run nginx with monit
  template: src=roles/monit/templates/monit/nginx.conf.j2 dest=/etc/monit/conf.d/nginx.conf
  notify: reload monit

- meta: flush_handlers
